apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: el-kube
  type: LoadBalancer # require to make external
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30000 # Port for the LoadBalancer
